import java.util.*;

public class DiccionarioDivisas {

    private static final Map<String, String> nombresDivisas = Map.ofEntries(
            Map.entry("USD", "Dólar estadounidense"),
            Map.entry("AED", "Dirham de los Emiratos Árabes Unidos"),
            Map.entry("AFN", "Afgani afgano"),
            Map.entry("ALL", "Lek albanés"),
            Map.entry("AMD", "Dram armenio"),
            Map.entry("ANG", "Florín antillano neerlandés"),
            Map.entry("AOA", "Kwanza angoleño"),
            Map.entry("ARS", "Peso argentino"),
            Map.entry("AUD", "Dólar australiano"),
            Map.entry("AWG", "Florín arubeño"),
            Map.entry("AZN", "Manat azerbaiyano"),
            Map.entry("BAM", "Marco convertible de Bosnia y Herzegovina"),
            Map.entry("BBD", "Dólar de Barbados"),
            Map.entry("BDT", "Taka bangladesí"),
            Map.entry("BGN", "Lev búlgaro"),
            Map.entry("BHD", "Dinar bareiní"),
            Map.entry("BIF", "Franco burundés"),
            Map.entry("BMD", "Dólar bermudeño"),
            Map.entry("BND", "Dólar de Brunéi"),
            Map.entry("BOB", "Boliviano de Bolivia"),
            Map.entry("BRL", "Real brasileño"),
            Map.entry("BSD", "Dólar bahameño"),
            Map.entry("BTN", "Ngultrum butanés"),
            Map.entry("BWP", "Pula botsuano"),
            Map.entry("BYN", "Rublo bielorruso"),
            Map.entry("BZD", "Dólar beliceño"),
            Map.entry("CAD", "Dólar canadiense"),
            Map.entry("CDF", "Franco congoleño"),
            Map.entry("CHF", "Franco suizo"),
            Map.entry("CLP", "Peso chileno"),
            Map.entry("CNY", "Yuan chino"),
            Map.entry("COP", "Peso colombiano"),
            Map.entry("CRC", "Colón costarricense"),
            Map.entry("CUP", "Peso cubano"),
            Map.entry("CVE", "Escudo caboverdiano"),
            Map.entry("CZK", "Corona checa"),
            Map.entry("DJF", "Franco yibutiano"),
            Map.entry("DKK", "Corona danesa"),
            Map.entry("DOP", "Peso dominicano"),
            Map.entry("DZD", "Dinar argelino"),
            Map.entry("EGP", "Libra egipcia"),
            Map.entry("ERN", "Nakfa eritreo"),
            Map.entry("ETB", "Birr etíope"),
            Map.entry("EUR", "Euro"),
            Map.entry("FJD", "Dólar fiyiano"),
            Map.entry("FKP", "Libra malvinense"),
            Map.entry("FOK", "Corona feroesa"),
            Map.entry("GBP", "Libra esterlina"),
            Map.entry("GEL", "Lari georgiano"),
            Map.entry("GGP", "Libra de Guernsey"),
            Map.entry("GHS", "Cedi ghanés"),
            Map.entry("GIP", "Libra de Gibraltar"),
            Map.entry("GMD", "Dalasi gambiano"),
            Map.entry("GNF", "Franco guineano"),
            Map.entry("GTQ", "Quetzal guatemalteco"),
            Map.entry("GYD", "Dólar guyanés"),
            Map.entry("HKD", "Dólar de Hong Kong"),
            Map.entry("HNL", "Lempira hondureña"),
            Map.entry("HRK", "Kuna croata"),
            Map.entry("HTG", "Gourde haitiano"),
            Map.entry("HUF", "Forint húngaro"),
            Map.entry("IDR", "Rupia indonesia"),
            Map.entry("ILS", "Nuevo séquel israelí"),
            Map.entry("IMP", "Libra de la Isla de Man"),
            Map.entry("INR", "Rupia india"),
            Map.entry("IQD", "Dinar iraquí"),
            Map.entry("IRR", "Rial iraní"),
            Map.entry("ISK", "Corona islandesa"),
            Map.entry("JEP", "Libra de Jersey"),
            Map.entry("JMD", "Dólar jamaiquino"),
            Map.entry("JOD", "Dinar jordano"),
            Map.entry("JPY", "Yen japonés"),
            Map.entry("KES", "Chelín keniano"),
            Map.entry("KGS", "Som kirguís"),
            Map.entry("KHR", "Riel camboyano"),
            Map.entry("KID", "Dólar de Kiribati"),
            Map.entry("KMF", "Franco comorense"),
            Map.entry("KRW", "Won surcoreano"),
            Map.entry("KWD", "Dinar kuwaití"),
            Map.entry("KYD", "Dólar de las Islas Caimán"),
            Map.entry("KZT", "Tenge kazajo"),
            Map.entry("LAK", "Kip laosiano"),
            Map.entry("LBP", "Libra libanesa"),
            Map.entry("LKR", "Rupia de Sri Lanka"),
            Map.entry("LRD", "Dólar liberiano"),
            Map.entry("LSL", "Loti lesotense"),
            Map.entry("LYD", "Dinar libio"),
            Map.entry("MAD", "Dirham marroquí"),
            Map.entry("MDL", "Leu moldavo"),
            Map.entry("MGA", "Ariary malgache"),
            Map.entry("MKD", "Denar macedonio"),
            Map.entry("MMK", "Kyat birmano"),
            Map.entry("MNT", "Tugrik mongol"),
            Map.entry("MOP", "Pataca de Macao"),
            Map.entry("MRU", "Ouguiya mauritana"),
            Map.entry("MUR", "Rupia mauriciana"),
            Map.entry("MVR", "Rufiyaa de Maldivas"),
            Map.entry("MWK", "Kwacha malauí"),
            Map.entry("MXN", "Peso mexicano"),
            Map.entry("MYR", "Ringgit malayo"),
            Map.entry("MZN", "Metical mozambiqueño"),
            Map.entry("NAD", "Dólar namibio"),
            Map.entry("NGN", "Naira nigeriano"),
            Map.entry("NIO", "Córdoba nicaragüense"),
            Map.entry("NOK", "Corona noruega"),
            Map.entry("NPR", "Rupia nepalí"),
            Map.entry("NZD", "Dólar neozelandés"),
            Map.entry("OMR", "Rial omaní"),
            Map.entry("PAB", "Balboa panameño"),
            Map.entry("PEN", "Sol peruano"),
            Map.entry("PGK", "Kina de Papúa Nueva Guinea"),
            Map.entry("PHP", "Peso filipino"),
            Map.entry("PKR", "Rupia pakistaní"),
            Map.entry("PLN", "Zloty polaco"),
            Map.entry("PYG", "Guaraní paraguayo"),
            Map.entry("QAR", "Rial catarí"),
            Map.entry("RON", "Leu rumano"),
            Map.entry("RSD", "Dinar serbio"),
            Map.entry("RUB", "Rublo ruso"),
            Map.entry("RWF", "Franco ruandés"),
            Map.entry("SAR", "Rial saudí"),
            Map.entry("SBD", "Dólar de las Islas Salomón"),
            Map.entry("SCR", "Rupia seychellense"),
            Map.entry("SDG", "Libra sudanesa"),
            Map.entry("SEK", "Corona sueca"),
            Map.entry("SGD", "Dólar de Singapur"),
            Map.entry("SHP", "Libra de Santa Elena"),
            Map.entry("SLE", "Leone de Sierra Leona (nuevo)"),
            Map.entry("SLL", "Leone de Sierra Leona (antiguo)"),
            Map.entry("SOS", "Chelín somalí"),
            Map.entry("SRD", "Dólar surinamés"),
            Map.entry("SSP", "Libra sursudanesa"),
            Map.entry("STN", "Dobra de Santo Tomé y Príncipe"),
            Map.entry("SYP", "Libra siria"),
            Map.entry("SZL", "Lilangeni suazi"),
            Map.entry("THB", "Baht tailandés"),
            Map.entry("TJS", "Somoni tayiko"),
            Map.entry("TMT", "Manat turcomano"),
            Map.entry("TND", "Dinar tunecino"),
            Map.entry("TOP", "Paʻanga tongano"),
            Map.entry("TRY", "Lira turca"),
            Map.entry("TTD", "Dólar de Trinidad y Tobago"),
            Map.entry("TVD", "Dólar de Tuvalu"),
            Map.entry("TWD", "Nuevo dólar taiwanés"),
            Map.entry("TZS", "Chelín tanzano"),
            Map.entry("UAH", "Grivna ucraniana"),
            Map.entry("UGX", "Chelín ugandés"),
            Map.entry("UYU", "Peso uruguayo"),
            Map.entry("UZS", "Som uzbeko"),
            Map.entry("VES", "Bolívar soberano venezolano"),
            Map.entry("VND", "Dong vietnamita"),
            Map.entry("VUV", "Vatu vanuatuense"),
            Map.entry("WST", "Tala samoana"),
            Map.entry("XAF", "Franco CFA de África Central"),
            Map.entry("XCD", "Dólar del Caribe Oriental"),
            Map.entry("XCG", "(No estándar - código no reconocido)"),
            Map.entry("XDR", "Derechos Especiales de Giro"),
            Map.entry("XOF", "Franco CFA de África Occidental"),
            Map.entry("XPF", "Franco CFP"),
            Map.entry("YER", "Rial yemení"),
            Map.entry("ZAR", "Rand sudafricano"),
            Map.entry("ZMW", "Kwacha zambiano"),
            Map.entry("ZWL", "Dólar zimbabuense")
    );

    public static void mostrarDivisas() {
        List<String> codigos = new ArrayList<>(nombresDivisas.keySet());
        Collections.sort(codigos); // Orden alfabético por código

        for (int i = 0; i < codigos.size(); i += 4) {
            String col1 = formatear(codigos, i);
            String col2 = formatear(codigos, i + 1);
            String col3 = formatear(codigos, i + 2);
            String col4 = formatear(codigos, i + 3);

            System.out.println(col1 + col2 + col3 + col4);
        }
    }

    private static String formatear(List<String> codigos, int index) {
        if (index < codigos.size()) {
            String codigo = codigos.get(index);
            String nombre = nombresDivisas.getOrDefault(codigo, "Nombre no disponible");
            return String.format("%-5s : %-35s", codigo, nombre);
        }
        return "";
    }
}
